### ISSUE TITLE
Improvement: Allow selection by Skill Level/Passion Level

### ISSUE THREAD

**Issue by PiggyWhiskey** [LokiVKlokeNaAndoke/RimWorld_Mod_AutoPriorities#2]
I don't even know if it's possible, to limit the pawns with set skills for a set priority.

i.e. PawnA has 2 in Medicine, but a Double Passion, PawnB has 5 in Medicine, PawnC has 2 but a single Passion.

33% Medicine, should select PawnA before the other 2 pawns (He'll get to level 5 faster)  
66% will select PawnA/PawnB

**Comment by Klok-e** [comment]
Thanks for your suggestion! I'll get to it when I finish my exams.
